### ISSUE TITLE
clangmm no longer compiles on windows

### ISSUE THREAD

**Issue by zalox** [cppit/libclangmm#9]
libclangmm does no longer compile on windows

**Comment by zalox** [comment]
@eidheim I will make sure this repo compiles on windows. Do you know how to compile without MSVS?

**Comment by eidheim** [comment]
No idea sorry, but I think there is a free version of MSVS? Visual Studio Code maybe?

**Comment by eidheim** [comment]
There is also a Visual Studio Community: https://www.visualstudio.com/vs-2015-product-editions

**Comment by zalox** [comment]
I will see if I find an easy way to do it without ms-software.

**Comment by eidheim** [comment]
Hope you figure it out. I used MinGW-w64 a couple of years ago, which is more updated than MinGW. However MinGW-w64 is less used it seems, so don't know how well it is supported by the various open source projects. Also MinGW-w64 had support for threads and c++14 (which MinGW lacked), however if you have troubles, we could go for boost.threads instead. But you might find better solutions than I did. Also not sure if MinGW supports regex either since its so old, but luckily boost has this as well. You can see some of the differences here: https://en.wikipedia.org/wiki/MinGW

Also, we might need Boost.PropertyTree in libclangmm to parse comments, which luckily also are exported in XML as well as HTML by libclang. The HTML-output from libclang was awful, but hopefully the XML is better. I will investigate this at some point. The current comment parse in libclangmm is a dirty hack btw:)

**Comment by eidheim** [comment]
Maybe Cygwin is the way to go (http://stackoverflow.com/a/4147985)? Might be that most if not all of the libraries are included in the cygwin distribution (https://cygwin.com/packages/package_list.html)?

**Comment by eidheim** [comment]
There is also a mingw-w64 package in cygwin that one could use (https://cygwin.com/packages/x86/mingw64-i686-gcc-g++/)?

**Comment by eidheim** [comment]
From https://en.wikipedia.org/wiki/Cygwin: "Cygwin is used heavily for porting many popular pieces of software to the Windows platform. It is used to compile Sun Java, OpenOffice.org, LibreOffice, and even web server software like Lighttpd and Hiawatha."
